import * as React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import CheckOnline from "../components/OnlineChecker";

import Menu from "../components/Index/Menu";

const Home: NextPage = () => {
    if (!CheckOnline()) alert("offline");

    return (
        <div className="">
            <Head>
                <title>The Flag Game</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="w-screen h-max">
                <Menu />
            </div>
        </div>
    );
};

export default Home;
